
#ALTER TABLE `USERS` DROP COLUMN `nominativo`;

#ALTER TABLE `USERS` DROP COLUMN `indirizzo`;

#ALTER TABLE `USERS` DROP COLUMN `provincia`;

#ALTER TABLE `USERS` DROP COLUMN `citta`;

#ALTER TABLE `USERS` DROP COLUMN `cap`;

#ALTER TABLE `USERS` DROP COLUMN `numeroCivico`;



#ALTER TABLE `USERS` DROP COLUMN `dataScadenza`;

#ALTER TABLE `USERS` DROP COLUMN `nFotoVisual`;

#ALTER TABLE `USERS` DROP COLUMN `nFotoMax`;

#ALTER TABLE `USERS` DROP COLUMN `flgMailFotoMax`;


#ALTER TABLE `USERS` DROP COLUMN `flgMailFotoScadenza`;

#ALTER TABLE `USERS` DROP COLUMN `flgMiniature`;








ALTER TABLE `USERS` ADD COLUMN `style` VARCHAR(60);

ALTER TABLE `USERS` ADD COLUMN `flgMl` INTEGER;

ALTER TABLE `USERS` ADD COLUMN `langMl` CHAR(2);

ALTER TABLE `USERS` ADD COLUMN `flgOperatore` INTEGER;

ALTER TABLE `USERS` ADD COLUMN `flgNews` INTEGER;

ALTER TABLE `USERS` ADD COLUMN `imgProfilo` VARCHAR(30);

ALTER TABLE `USERS` ADD COLUMN `cittaNascita` VARCHAR(30);

ALTER TABLE `USERS` ADD COLUMN `provinciaNascita` VARCHAR(4);

ALTER TABLE `USERS` ADD COLUMN `elencoIpAbilitati` VARCHAR(254);


ALTER TABLE `USERS` MODIFY `pwd` VARCHAR(512);

ALTER TABLE `USERS` MODIFY `nota` TEXT;


ALTER TABLE `USERS` MODIFY `indirizzoSped` VARCHAR(60);

ALTER TABLE `USERS` MODIFY `provinciaSped` VARCHAR(30);

ALTER TABLE `USERS` MODIFY `cittaSped` VARCHAR(30);

ALTER TABLE `USERS` MODIFY `capSped` VARCHAR(10);

ALTER TABLE `USERS` MODIFY `presso` VARCHAR(60);

ALTER TABLE `USERS` MODIFY `controlCode` VARCHAR(30);

ALTER TABLE `USERS` MODIFY `pIva` VARCHAR(15);


ALTER TABLE `USERS` MODIFY `currentIp` CHAR(60);

ALTER TABLE `USERS` MODIFY `createIp` CHAR(60);

ALTER TABLE `USERS` MODIFY `oldPwd` TEXT;

ALTER TABLE `USERS` MODIFY `flgChangeLog` INTEGER;

ALTER TABLE `USERS` MODIFY `pwdSuper` VARCHAR(512);
